### ISSUE TITLE
Неверное отображение баланса при пополнении карты на сумму недостающей до отметки  максимального баланса..

### ISSUE THREAD

**Issue by figlovskayad** [Soldatova2406/javaqa-team-diplom-2#2]
# Описание
Баланс должен увеличиваться на сумму пополнения, если же операция может привести к некорректному состоянию счета, баланс остается неизменным.

# Локация дефекта
https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/9a97b3cbdd3112ff61c24d893d338a9f609f4fb8/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72-L73

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72-L73) в IDEA.
2. Создать объект new SavingAccount с initialBalance (начальный баланс) равном 2000 и максимальным в 10000 в классе SavingAccountTest.
3. Указать в методе add (пополнение баланса) сумму равную 8000.
4. В Assertions.assertEquals указать expected (ожидаемый результат) 10000, в actual (фактический) метод getBalance
5. Запустить тест.
6. Посмотреть на вывод в консоли.

*Ожидаемый результат:*  тест проходит.
*Фактический результат:* консоль выводит фактический результат 2000 , ожидаемый 10000.
# Тест
https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/9a97b3cbdd3112ff61c24d893d338a9f609f4fb8/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L38-L48
<img width="494" alt="Снимок экрана 2023-05-23 в 18 21 27" src="https://github.com/Soldatova2406/javaqa-team-diplom-2/assets/126390875/71abeac6-60e2-4cdf-ae0e-1b0ec44d495d">

# Окружение
* **Операционная система:** macOS Ventura 13.2
* **IDE:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Soldatova2406** [comment]
Ошибка исправлена, подсчитывается корректно.
