### ISSUE TITLE
Неверное отображение баланса при покупке на сумму превышающую начальный баланс.

### ISSUE THREAD

**Issue by figlovskayad** [Soldatova2406/javaqa-team-diplom-2#3]
# Описание
Баланс должен уменьшаться на сумму покупки. Если это приводит к некорректному состоянию поля, то операция завершится ничего не поменяв на счете.

# Локация дефекта
https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/9a97b3cbdd3112ff61c24d893d338a9f609f4fb8/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L48-L52

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72-L73) в IDEA.
2. Создать объект new SavingAccount с initialBalance (начальный баланс) равном 2000 в классе SavingAccountTest.
3. Указать в методе pay (покупка) сумму равную 3000.
4. В Assertions.assertEquals указать expected (ожидаемый результат) 2000, в actual (фактический) метод getBalance
5. Запустить тест.
6. Посмотреть на вывод в консоли.

*Ожидаемый результат:*  тест проходит.
*Фактический результат:* консоль выводит фактический результат-1000, ожидаемый 2000.
# Тест
https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/9a97b3cbdd3112ff61c24d893d338a9f609f4fb8/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L66-L76
<img width="470" alt="Снимок экрана 2023-05-23 в 18 30 51" src="https://github.com/Soldatova2406/javaqa-team-diplom-2/assets/126390875/ff1f4173-5a84-4971-82ee-9cfe3a7e9f8c">

# Окружение
* **Операционная система:** macOS Ventura 13.2
* **IDE:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Soldatova2406** [comment]
Исправлено, подсчитывается верно.
