### ISSUE TITLE
Неверный подсчет баланса после покупки

### ISSUE THREAD

**Issue by Soldatova2406** [Soldatova2406/javaqa-team-diplom-2#5]
## Описание
В результате успешного вызова этого метода, баланс должен уменьшиться на сумму покупки. Если же операция может привести к некорректному состоянию счёта (например, баланс может уйти меньше чем лимит), то операция должна завершиться вернув false и ничего не поменяв на счёте.

## Локация дефекта

https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/5413f87def0b315220e980be79a09e00b5ac3f19/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40-L52

 
## Шаги воспроизведения
1. Открыть в IDEA: https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/5413f87def0b315220e980be79a09e00b5ac3f19/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40-L52 
2. Создать объект new CreditAccount с initialBalance (начальный баланс) равном 1000 и creditLimit в 5000 и  rate 15 в классе CreditAccountTest.
3. Указать в методе pay (совершение покупки) сумму равную 500.
В Assertions.assertEquals указать expected (ожидаемый результат) 500, в actual (фактический) метод getBalance
Запустить тест.
Посмотреть на вывод в консоли.
Ожидаемый результат: тест проходит.
Фактический результат: консоль выводит фактический результат -500 , ожидаемый 500.

### Тест

https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/5413f87def0b315220e980be79a09e00b5ac3f19/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L35-L45

![image](https://github.com/Soldatova2406/javaqa-team-diplom-2/assets/121085750/77e068ab-79f1-4ae2-9c24-227daf438c87)

### Окружение

- Windows 10
- IDE: IntelliJ IDEA 2022.3.3 (Community Edition)
- Java: OpenJDK 11

**Comment by figlovskayad** [comment]
Исправлено
