### ISSUE TITLE
Неверный подсчет баланса после пополнения

### ISSUE THREAD

**Issue by Soldatova2406** [Soldatova2406/javaqa-team-diplom-2#6]
## Описание
Операция пополнения карты на указанную сумму. В результате успешного вызова этого метода, баланс должен увеличиться на сумму покупки. Если же операция может привести к некорректному состоянию счёта, то операция должна завершиться вернув false и ничего не поменяв на счёте.

## Локация дефекта

https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/5413f87def0b315220e980be79a09e00b5ac3f19/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L65-L72

 
## Шаги воспроизведения
1. Открыть в IDEA проект
2. Создать объект new CreditAccount с initialBalance (начальный баланс) равном 500 и creditLimit в 5000 и  rate 15 в классе CreditAccountTest.
3. Указать в методе add (пополнение) сумму равную 1000.
В Assertions.assertEquals указать expected (ожидаемый результат) 1500, в actual (фактический) метод getBalance
Запустить тест.
Посмотреть на вывод в консоли.
Ожидаемый результат: тест проходит.
Фактический результат: консоль выводит фактический результат 1000 , ожидаемый 1500.

### Тест
https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/5413f87def0b315220e980be79a09e00b5ac3f19/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L83-L94
![image](https://github.com/Soldatova2406/javaqa-team-diplom-2/assets/121085750/4ff0adab-2dff-4c18-bdfe-edfbcab9825e)

### Окружение

- Windows 10
- IDE: IntelliJ IDEA 2022.3.3 (Community Edition)
- Java: OpenJDK 11

**Comment by figlovskayad** [comment]
Исправлено
