### ISSUE TITLE
Неверный подсчет процентов при отрицательном балансе.

### ISSUE THREAD

**Issue by Soldatova2406** [Soldatova2406/javaqa-team-diplom-2#7]
## Описание
Операция расчёта процентов на отрицательный баланс счёта при условии, что счёт не будет меняться год. Сумма процентов приводится к целому числу через отбрасывание дробной части (так и работает целочисленное деление).

## Локация дефекта

https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/5413f87def0b315220e980be79a09e00b5ac3f19/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82-L85
 
## Шаги воспроизведения
1. Открыть в IDEA проект
2. Создать объект new CreditAccount с initialBalance (начальный баланс) равном -200 и creditLimit в 5000 и  rate 15 в классе CreditAccountTest.
3. Использовать метод yearChange
В Assertions.assertEquals указать expected (ожидаемый результат) -230(200 изначальный плюс проценты 30), в actual (фактический) метод getBalance
Запустить тест.
Посмотреть на вывод в консоли.
Ожидаемый результат: тест проходит.
Фактический результат: консоль выводит фактический результат -200 , ожидаемый -230.

### Тест
https://github.com/Soldatova2406/javaqa-team-diplom-2/blob/5413f87def0b315220e980be79a09e00b5ac3f19/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L109-L119
![image](https://github.com/Soldatova2406/javaqa-team-diplom-2/assets/121085750/26f12acc-ec1d-415b-96f5-d16b6425d2eb)

### Окружение

- Windows 10
- IDE: IntelliJ IDEA 2022.3.3 (Community Edition)
- Java: OpenJDK 11

**Comment by figlovskayad** [comment]
Исправлено
